version: '3.8'

services:
  url-shortener:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - BASE_URL=http://localhost:8080
      - REDIS_ENABLED=false
    restart: unless-stopped
    networks:
      - url-shortener-network

  # Optional Redis service (uncomment to enable)
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     - url-shortener-network

networks:
  url-shortener-network:
    driver: bridge

# volumes:
#   redis-data:

