version: 2
updates:
  # Backend Go dependencies
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    assignees:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "go"
      - "backend"
    commit-message:
      prefix: "chore"
      include: "scope"
    pull-request-branch-name:
      separator: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Shared libraries Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "go"
      - "shared"
    commit-message:
      prefix: "chore"

  # API Gateway Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "go"
      - "api-gateway"
    commit-message:
      prefix: "chore"

  # User Service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/user-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "go"
      - "user-service"
    commit-message:
      prefix: "chore"

  # Course Service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/course-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "go"
      - "course-service"
    commit-message:
      prefix: "chore"

  # Progress Service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/services/progress-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "go"
      - "progress-service"
    commit-message:
      prefix: "chore"

  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "DimaJoyti"
    assignees:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "npm"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"
    versioning-strategy: increase
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Terraform dependencies
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
    commit-message:
      prefix: "chore"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "docker"
    directory: "/services/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "DimaJoyti"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci-cd"
    commit-message:
      prefix: "chore"
      include: "scope"

