apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gopro

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

commonAnnotations:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

configMapGenerator:
  - name: frontend-config
    behavior: merge
    literals:
      - api-url=https://dev-api.gopro.com
      - environment=development

replicas:
  - name: backend
    count: 2
  - name: frontend
    count: 1

images:
  - name: ghcr.io/dimajoyti/go-pro/backend
    newTag: develop
  - name: ghcr.io/dimajoyti/go-pro/frontend
    newTag: develop

