apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gopro

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

commonAnnotations:
  environment: production

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: frontend-config
    behavior: merge
    literals:
      - api-url=https://api.gopro.com
      - environment=production

replicas:
  - name: backend
    count: 5
  - name: frontend
    count: 3

images:
  - name: ghcr.io/dimajoyti/go-pro/backend
    newTag: main
  - name: ghcr.io/dimajoyti/go-pro/frontend
    newTag: main

