# EKS Cluster Configuration for GO-PRO
# This file can be used with eksctl to create an EKS cluster

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: gopro-dev-cluster
  region: us-east-1
  version: "1.28"
  tags:
    Environment: development
    Project: gopro
    ManagedBy: eksctl

# VPC Configuration
vpc:
  cidr: 10.0.0.0/16
  nat:
    gateway: Single  # Use HighlyAvailable for production
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

# IAM Configuration
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true
    - metadata:
        name: external-dns
        namespace: kube-system
      wellKnownPolicies:
        externalDNS: true

# Managed Node Groups
managedNodeGroups:
  - name: gopro-dev-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 1
    maxSize: 5
    volumeSize: 50
    volumeType: gp3
    privateNetworking: true
    ssh:
      allow: false
    labels:
      role: worker
      environment: development
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/gopro-dev-cluster: "owned"
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        albIngress: true
        xRay: true
        cloudWatch: true

# Addons
addons:
  - name: vpc-cni
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - name: coredns
    version: latest
  - name: kube-proxy
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    wellKnownPolicies:
      ebsCSIController: true

# CloudWatch Logging
cloudWatch:
  clusterLogging:
    enableTypes:
      - api
      - audit
      - authenticator
      - controllerManager
      - scheduler
    logRetentionInDays: 7

# Fargate Profiles (optional)
# fargateProfiles:
#   - name: gopro-fargate
#     selectors:
#       - namespace: fargate
#     tags:
#       Environment: development

# Git Ops (optional)
# gitops:
#   flux:
#     gitProvider: github
#     flags:
#       owner: DimaJoyti
#       repository: gopro
#       private: true
#       branch: main
#       namespace: flux-system
#       path: k8s/clusters/dev

